sudo: false
language: ruby

rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.10

before_install:
  - gem update bundler

gemfile:
  - Gemfile
  - gemfiles/fluentd_v0.10.gemfile
  - gemfiles/fluentd_v0.12.gemfile
  - gemfiles/fluentd_v0.14.gemfile

matrix:
  include:
    - rvm: 2.0.0
      gemfile: gemfiles/fluentd_v0.10.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/fluentd_v0.12.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/fluentd_v0.12.gemfile
  exclude:
    - rvm: 2.3.1
      gemfile: gemfiles/fluentd_v0.10.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/fluentd_v0.10.gemfile
